server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/borrow_books?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root10086
    driver-class-name: com.mysql.cj.jdbc.Driver
